version: '3.6'

services:
  mysql:
    container_name: mysql-book-load-ms
    image: mysql:8.0
    restart: always
    ports:
      - 33066:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookDB
